"use client";
import { useEffect, useState } from "react";

type Point={date:string;count:number};
export type DashboardData={totals:{staff:number;visits:number;consultations:number;applications:number};visitSeries:Point[];consultationSeries:Point[];applicationSeries:Point[];updatedAt:string};

function Chart({title,points,color}:{title:string;points:Point[];color:string}){const max=Math.max(1,...points.map(p=>p.count));return <article className="admin-card live-chart"><header><div><h2>{title}</h2><span>30 ngày gần nhất</span></div><strong>{points.reduce((sum,p)=>sum+p.count,0).toLocaleString("vi-VN")}</strong></header><div className="line-bars">{points.length?points.map(point=><div className="line-bars__item" key={point.date} title={`${new Date(point.date).toLocaleDateString("vi-VN")}: ${point.count}`}><i style={{height:`${Math.max(5,point.count/max*100)}%`,background:color}}/><span>{new Date(point.date).getDate()}</span></div>):<p>Chưa có dữ liệu.</p>}</div></article>}

export function RealtimeDashboard({initialData}:{initialData:DashboardData}){const [data,setData]=useState(initialData);const [online,setOnline]=useState(true);useEffect(()=>{let active=true;const refresh=async()=>{try{const response=await fetch("/api/cms/dashboard",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error();if(active){setData(payload.data);setOnline(true)}}catch{if(active)setOnline(false)}};const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer)}},[]);const cards=[{label:"Tổng số nhân sự",value:data.totals.staff,tone:"green",icon:"♙"},{label:"Tổng lượt truy cập",value:data.totals.visits,tone:"blue",icon:"♧"},{label:"Tổng lượt đặt lịch",value:data.totals.consultations,tone:"purple",icon:"◷"},{label:"Tổng hồ sơ đăng ký",value:data.totals.applications,tone:"orange",icon:"▧"}];const total=Math.max(1,data.totals.visits+data.totals.consultations+data.totals.applications);const consult=(data.totals.consultations/total*100);const applications=(data.totals.applications/total*100);return <><div className="live-status"><i className={online?"online":"offline"}/><span>{online?"Đang cập nhật trực tiếp":"Mất kết nối cập nhật"}</span><time>{new Date(data.updatedAt).toLocaleTimeString("vi-VN")}</time></div><section className="metric-grid">{cards.map(card=><article className={`metric-card ${card.tone}`} key={card.label}><div><span>{card.label}</span><strong>{card.value.toLocaleString("vi-VN")}</strong></div><b>{card.icon}</b></article>)}</section><section className="dashboard-analysis"><article className="admin-card donut-card"><h2>Thống kê phân loại tương tác</h2><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#2baf90 0 ${consult}%,#4d87f7 ${consult}% ${consult+applications}%,#f5a20a ${consult+applications}% 100%)`}}><span>{total.toLocaleString("vi-VN")}<small>Tổng</small></span></div><ul><li><i className="green"/>Lịch tư vấn <b>{data.totals.consultations}</b></li><li><i className="blue"/>Hồ sơ đăng ký <b>{data.totals.applications}</b></li><li><i className="orange"/>Lượt truy cập <b>{data.totals.visits}</b></li></ul></div></article><Chart title="Thống kê lượt truy cập theo ngày" points={data.visitSeries} color="#08bd88"/></section><section className="charts-grid secondary-charts"><Chart title="Lịch tư vấn" points={data.consultationSeries} color="#5375e2"/><Chart title="Hồ sơ đăng ký" points={data.applicationSeries} color="#f0a33b"/></section></>}
