import Image from "next/image";
import Link from "@/i18n/components/LocalizedLink";
import { ArrowUpRight } from "lucide-react";
import { SiteHeader } from "@/shared/components/layout/SiteHeader";
import { SiteFooter } from "@/shared/components/layout/SiteFooter";
import { NextStepCTA } from "@/features/content/components/NextStepCTA";
import { RevealOnScroll } from "@/shared/components/layout/RevealOnScroll";
import styles from "./StudentSuccessPage.module.css";

export const metadata={title:"Hành trình người học | Viện Sau Đại học",description:"Hệ sinh thái học tập, hỗ trợ và phát triển nghề nghiệp đồng hành cùng người học Viện Sau Đại học."};
const services=[
  ["Hỗ trợ người học","Đồng hành trong thủ tục học vụ, tư vấn và giải đáp để mỗi người học an tâm tập trung vào hành trình học tập.","https://www.vlu.edu.vn/dynamic/ho-tro-sinh-vien?mode=preview","/images/pages/student-success/content/hotrohocvien.avif"],
  ["Tài nguyên học tập","Tiếp cận thư viện, học liệu số, không gian nghiên cứu và các công cụ hỗ trợ học tập linh hoạt.","/resources","/images/pages/student-success/content/tainguyen.JPG"],
  ["Phát triển sự nghiệp","Kết nối chuyên gia, doanh nghiệp và cơ hội nghề nghiệp phù hợp với định hướng phát triển chuyên môn.","https://www.vlu.edu.vn/admissions/professional-career-support","/images/pages/student-success/content/sunghiep.PNG"],
  ["Cộng đồng cựu người học","Mạng lưới kết nối tri thức, kinh nghiệm và những cơ hội hợp tác tiếp tục sau khi hoàn thành chương trình.","https://alumni.vlu.edu.vn/","/images/pages/student-success/content/csv.jpg"],
  ["Seminar & Hoạt động học thuật","Không gian trao đổi chuyên môn giúp người học tiếp cận góc nhìn mới và mở rộng mạng lưới học thuật.","https://www.vlu.edu.vn/life-at-vlu/it-and-technology","/images/pages/student-success/content/hocthuat.jpg"],
  ["Hoạt động ngoại khóa","Những hành trình phát triển truyền cảm hứng từ cộng đồng người học và cựu người học Viện Sau Đại học.","https://www.vlu.edu.vn/life-at-vlu/student-clubs","/images/pages/student-success/content/nk.jpg"],
] as const;

export default function StudentSuccessPage(){return <main className={styles.page} id="main-content"><RevealOnScroll/><SiteHeader compact/>
  <section className={styles.hero}><Image src="/images/pages/student-success/content/banner.JPG" alt="Cộng đồng người học Viện Sau Đại học" fill priority sizes="100vw" style={{zIndex:0}}/><div className={styles.heroShade} style={{zIndex:1}}/><div className={styles.heroCopy} style={{position:"relative",zIndex:2}}><p>HÀNH TRÌNH NGƯỜI HỌC · Viện Sau Đại học</p><h1>HỌC SÂU HƠN.<br/>KẾT NỐI XA HƠN.</h1><span>Một cộng đồng học thuật năng động, nơi mỗi người học được hỗ trợ để phát triển chuyên môn, mở rộng quan hệ và tạo dấu ấn riêng.</span></div></section>
  <section className={styles.zigzag}><figure><Image src="/images/pages/student-success/content/phattrien.PNG" alt="Hoạt động học thuật của người học" fill sizes="(max-width:800px) 100vw,50vw"/></figure><div><p>01 · HỌC TẬP & PHÁT TRIỂN</p><h2>Làm chủ hành trình học thuật</h2><span>Người học được tiếp cận giảng viên, chuyên gia, học liệu và các hoạt động chuyên môn để phát triển chiều sâu kiến thức, tư duy nghiên cứu và khả năng giải quyết vấn đề thực tiễn.</span><Link href="https://www.vlu.edu.vn/life-at-vlu/it-and-technology">Khám phá ngay <ArrowUpRight/></Link></div></section>
  <section className={`${styles.zigzag} ${styles.reverse}`}><figure><Image src="/images/pages/student-success/content/hoctap.JPG" alt="Kết nối chuyên gia và người học" fill sizes="(max-width:800px) 100vw,50vw"/></figure><div><p>02 · CỘNG ĐỒNG & KẾT NỐI</p><h2>Phát triển cùng cộng đồng</h2><span>Những cuộc gặp gỡ với giảng viên, nhà quản lý, chuyên gia và các người học giàu kinh nghiệm tạo nên một môi trường trao đổi cởi mở, đa chiều và giàu giá trị.</span><Link href="https://www.vlu.edu.vn/sustainability/homepage-sustainability/homepage">Tìm hiểu cộng đồng <ArrowUpRight/></Link></div></section>
  <section className={styles.experience}><header><p>03 · TRẢI NGHIỆM NGƯỜI HỌC</p><h2>Đời sống tại Viện Sau Đại học</h2><span>Hệ sinh thái hỗ trợ được thiết kế để người học chủ động học tập, kết nối và phát triển trong suốt chương trình.</span></header><div className={styles.cardGrid}>{services.map(([title,copy,href,image])=><Link href={href} className={styles.card} key={title}><figure><Image src={image} alt={title} fill sizes="(max-width:700px) 100vw,33vw"/></figure><h3>{title}</h3><p>{copy}</p><b>Tìm hiểu thêm <ArrowUpRight/></b></Link>)}</div></section>
  <section className={styles.moments}><header><p>04 · Viện Sau Đại học MOMENTS</p><h2>Khoảnh khắc người học</h2></header><div><figure><Image src="/images/pages/student-success/content/kk7.jpg" alt="Khoảnh khắc học tập tại Viện Sau Đại học" fill sizes="(max-width:600px) 100vw,33vw"/></figure><figure><Image src="/images/pages/student-success/content/kk2.avif" alt="Người học Viện Sau Đại học tại khuôn viên" fill sizes="(max-width:600px) 100vw,33vw"/></figure><figure><Image src="/images/pages/student-success/content/kk3.jpg" alt="Hoạt động cộng đồng của người học Viện Sau Đại học" fill sizes="(max-width:600px) 100vw,33vw"/></figure><figure><Image src="/images/pages/student-success/content/kk5.jpg" alt="Khoảnh khắc chúc mừng của người học" fill sizes="(max-width:600px) 100vw,33vw"/></figure><figure><Image src="/images/pages/student-success/content/kk6.jpg" alt="Cộng đồng cựu người học Viện Sau Đại học" fill sizes="(max-width:600px) 100vw,33vw"/></figure><figure><Image src="/images/pages/student-success/content/kk4.jpg" alt="Hoạt động học thuật tại Viện Sau Đại học" fill sizes="(max-width:600px) 100vw,33vw"/></figure></div></section>
  <NextStepCTA/><SiteFooter/>
  </main>}
