from pathlib import Path
from datetime import date
import json
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT=Path(r'C:\Users\lepha\VGG')
BA=ROOT/'docs'/'ba'; D='2026-09-04'; PROJECT='VGG'
for p in [BA/'01-business',BA/'02-requirements',BA/'03-diagrams',BA/'04-uat',BA/'05-reports',BA/'archive',ROOT/'work'/'ba-build'/'rendered']:
    p.mkdir(parents=True,exist_ok=True)

sources=[
 ('SRC-01','Tài liệu','README.md','Tổng quan, cấu trúc, vai trò và hướng dẫn chạy'),
 ('SRC-02','Tài liệu','PROJECT_CONTEXT.md','Kiến trúc, route, module và mô hình dữ liệu'),
 ('SRC-03','Tài liệu','docs/handover/*','Triển khai, bảo mật, sao lưu, vận hành; các tuyên bố nghiệm thu chưa có minh chứng được đánh dấu cần xác nhận'),
 ('SRC-04','Mã nguồn','backend/prisma/schema.prisma','Mô hình dữ liệu và enum quan sát được'),
 ('SRC-05','Mã nguồn','backend/src/modules/*','API, validation, RBAC và luồng xử lý quan sát được'),
 ('SRC-06','Mã nguồn','admin/src/app và admin/src/components','Màn hình quản trị, trình soạn thảo, upload, phân quyền quan sát được'),
 ('SRC-07','Mã nguồn/Giao diện','frontend/src/app và frontend/src/features','Trang công khai, biểu mẫu, song ngữ và điều hướng quan sát được'),
 ('SRC-08','Cấu hình công khai','package.json, compose.yaml, *.env.example','Phụ thuộc kỹ thuật; không đọc giá trị bí mật trong .env'),
]

roles=[
 ('ROL-01','Khách truy cập','Không đăng nhập','Xem nội dung công khai; gửi yêu cầu tư vấn; tải tài nguyên đã công bố.'),
 ('ROL-02','QTV Cấp 2','ADMIN_LEVEL_2','Dashboard, tin tức, tài nguyên, tư vấn; không quản lý nhân sự.'),
 ('ROL-03','QTV Cấp 1','SUPER_ADMIN','Toàn quyền, gồm quản lý tài khoản/role và nhật ký.'),
]

reqs=[
('PUB-001','Cổng công khai','ROL-01','Xem trang song ngữ','Là khách truy cập, tôi muốn xem nội dung VI/EN để tiếp cận thông tin phù hợp.','Hệ thống phải cung cấp tuyến /vi và /en và duy trì locale khi điều hướng.','BR-01','Given locale hợp lệ When mở trang Then nội dung theo locale; Given locale không hỗ trợ When truy cập Then xử lý fallback/404 theo cấu hình; Given khách công khai Then không yêu cầu đăng nhập.','Must','M','Quan sát','SRC-02,SRC-07','Phạm vi dịch thuật đầy đủ cần xác nhận'),
('PUB-002','Cổng công khai','ROL-01','Tra cứu chương trình','Là người học, tôi muốn tìm chương trình phù hợp.','Hệ thống phải hiển thị danh mục chương trình và hỗ trợ tìm/lọc theo dữ liệu hiện có.','BR-02','Given dữ liệu hợp lệ When tìm/lọc Then chỉ hiện kết quả phù hợp; Given không có kết quả Then hiển thị trạng thái rỗng; Given khách công khai Then được phép truy cập.','Must','M','Quan sát','SRC-02,SRC-07','Dữ liệu hiện phần lớn tĩnh'),
('PUB-003','Cổng công khai','ROL-01','Xem tin đã xuất bản','Là khách truy cập, tôi muốn xem danh sách và chi tiết tin đã công bố.','API công khai chỉ được trả tin trạng thái PUBLISHED và đúng điều kiện thời gian công bố.','BR-03','Given tin PUBLISHED hợp lệ When mở danh sách/slug Then hiển thị; Given DRAFT/ARCHIVED When gọi công khai Then không trả nội dung; Given slug không tồn tại Then trả 404.','Must','M','Quan sát','SRC-02,SRC-05,SRC-07',''),
('PUB-004','Cổng công khai','ROL-01','Tải tài nguyên công khai','Là khách truy cập, tôi muốn tìm và tải tài liệu đã công bố.','Hệ thống phải liệt kê tài nguyên công khai và phân phối tệp qua proxy nội bộ.','BR-04','Given tài nguyên PUBLISHED When chọn tải Then trả đúng tệp; Given tài nguyên không tồn tại/không công bố Then từ chối; Given lỗi kho tệp Then thông báo an toàn.','Must','M','Quan sát','SRC-02,SRC-05,SRC-07',''),
('CON-001','Tư vấn','ROL-01','Gửi yêu cầu tư vấn','Là khách truy cập, tôi muốn gửi thông tin liên hệ để được tư vấn.','Hệ thống phải kiểm tra dữ liệu bắt buộc, chống bot cơ bản và ghi nhận yêu cầu tư vấn.','BR-05','Given dữ liệu hợp lệ When gửi Then tạo yêu cầu trạng thái NEW; Given thiếu/sai dữ liệu When gửi Then báo lỗi trường; Given vượt giới hạn tần suất Then từ chối có kiểm soát.','Must','M','Quan sát','SRC-02,SRC-05,SRC-07','Cơ sở pháp lý/đồng ý xử lý dữ liệu cần xác nhận'),
('AUTH-001','Xác thực','ROL-02,ROL-03','Đăng nhập quản trị','Là quản trị viên, tôi muốn đăng nhập an toàn.','Hệ thống phải xác thực tài khoản, trạng thái và tạo phiên bằng cookie HttpOnly.','BR-06','Given tài khoản hợp lệ ACTIVE When đăng nhập Then tạo phiên; Given sai thông tin When đăng nhập Then không tiết lộ tài khoản tồn tại; Given tài khoản LOCKED/INACTIVE Then từ chối; Given vượt rate limit Then chặn tạm thời.','Must','L','Quan sát','SRC-02,SRC-05,SRC-06',''),
('AUTH-002','Xác thực','ROL-02,ROL-03','Đổi mật khẩu bắt buộc','Là quản trị viên mới, tôi phải đổi mật khẩu trước khi sử dụng hệ thống.','Hệ thống phải buộc đổi mật khẩu khi mustChangePassword=true và vô hiệu hóa phiên phù hợp sau thay đổi.','BR-07','Given cờ bắt buộc đổi When đăng nhập Then chuyển đến trang đổi mật khẩu; Given mật khẩu mới không đạt chuẩn Then từ chối; Given đổi thành công Then cho phép tiếp tục theo quyền.','Must','M','Quan sát','SRC-02,SRC-04,SRC-06','Chính sách độ mạnh cần xác nhận'),
('NEWS-001','Tin tức','ROL-02,ROL-03','Tạo tin nháp','Là biên tập viên, tôi muốn tạo tin nháp để biên soạn.','Người có news.create phải tạo được bài với tiêu đề, slug, locale, danh mục và nội dung hợp lệ.','BR-08','Given có news.create và dữ liệu hợp lệ When lưu Then tạo DRAFT và audit; Given slug trùng/dữ liệu sai Then báo lỗi; Given không có quyền Then trả 403.','Must','M','Quan sát','SRC-05,SRC-06','Quy trình duyệt nội dung cần xác nhận'),
('NEWS-002','Tin tức','ROL-02,ROL-03','Soạn nội dung định dạng','Là biên tập viên, tôi muốn dán/định dạng văn bản và ảnh để giữ bố cục bài.','Trình soạn thảo phải hỗ trợ định dạng cho phép và làm sạch HTML trước khi lưu/hiển thị.','BR-09','Given nội dung định dạng hợp lệ When dán/lưu Then giữ cấu trúc được hỗ trợ; Given HTML nguy hiểm Then loại bỏ; Given ảnh clipboard hợp lệ When dán Then upload và chèn URL; Given upload lỗi Then giữ nội dung khác và báo lỗi.','Must','L','Quan sát','SRC-05,SRC-06','Hành vi clipboard mới là quan sát code, chưa phải yêu cầu phê duyệt'),
('NEWS-003','Tin tức','ROL-02,ROL-03','Tải ảnh bài viết','Là biên tập viên, tôi muốn tải ảnh từ máy cá nhân.','Hệ thống phải nhận JPG/PNG/WebP/AVIF tối đa 8 MB và lưu trong kho đối tượng.','BR-10','Given tệp hợp lệ và có news.create/update When tải Then trả URL media; Given sai loại/quá 8 MB Then từ chối; Given không đăng nhập/không quyền Then 401/403.','Must','M','Quan sát','SRC-05,SRC-06',''),
('NEWS-004','Tin tức','ROL-02,ROL-03','Xuất bản tin','Là biên tập viên có quyền, tôi muốn xuất bản tin để công khai.','Người có news.update phải chuyển bài sang PUBLISHED và thiết lập thời điểm công bố hợp lệ.','BR-03','Given bài hợp lệ và có quyền When xuất bản Then bài xuất hiện công khai; Given thiếu nội dung bắt buộc When xuất bản Then từ chối; Given không quyền Then 403.','Must','M','Quan sát','SRC-05,SRC-06','Phân tách người soạn/người duyệt cần xác nhận'),
('NEWS-005','Tin tức','ROL-02,ROL-03','Lưu trữ tin','Là quản trị viên, tôi muốn ngừng công khai bài mà không mất lịch sử.','Thao tác xóa tin phải chuyển trạng thái ARCHIVED và ghi audit.','BR-11','Given có news.delete When xóa Then trạng thái ARCHIVED; Given bài đã archived When xóa lại Then xử lý idempotent hoặc báo phù hợp; Given không quyền Then 403.','Should','S','Quan sát','SRC-05',''),
('RES-001','Tài nguyên','ROL-02,ROL-03','Tạo và tải tài nguyên','Là quản trị viên, tôi muốn đăng tệp tài nguyên có metadata.','Người có resources.create phải tải tệp được phép và tạo bản ghi gắn danh mục.','BR-12','Given PDF/Word/Excel/JPEG/PNG hợp lệ và có quyền When tải/lưu Then tạo bản ghi; Given loại sai/quá ngưỡng Then từ chối; Given danh mục không tồn tại Then từ chối; Given không quyền Then 403.','Must','L','Quan sát','SRC-05,SRC-06','Backend 50 MB, Admin mặc định 25 MB: cần thống nhất'),
('RES-002','Tài nguyên','ROL-02,ROL-03','Quản lý danh mục tài nguyên','Là quản trị viên, tôi muốn tạo/sửa/xóa danh mục.','Hệ thống phải bảo toàn ràng buộc khi danh mục còn tài nguyên tham chiếu.','BR-13','Given tên hợp lệ duy nhất When tạo/sửa Then lưu; Given tên trùng Then báo lỗi; Given danh mục đang được dùng When xóa Then từ chối; Given không quyền Then 403.','Should','M','Quan sát','SRC-05',''),
('RES-003','Tài nguyên','ROL-02,ROL-03','Xóa tài nguyên','Là quản trị viên, tôi muốn loại bỏ tài nguyên lỗi thời.','Người có resources.delete có thể xóa bản ghi tài nguyên; tác động lên tệp vật lý phải được xác định.','BR-14','Given có quyền và ID tồn tại When xóa Then bản ghi không còn được trả công khai và có audit; Given ID sai Then 404; Given không quyền Then 403.','Should','M','Quan sát/Cần xác nhận','SRC-05','Code xóa cứng bản ghi; chính sách lưu trữ và xóa object cần xác nhận'),
('CON-002','Tư vấn','ROL-02,ROL-03','Danh sách tư vấn','Là cán bộ, tôi muốn xem và lọc yêu cầu tư vấn.','Người có consultations.view phải xem danh sách theo bộ lọc/phân trang được hỗ trợ.','BR-15','Given có quyền When mở/lọc Then trả dữ liệu phù hợp; Given bộ lọc sai Then báo lỗi; Given không quyền Then 403.','Must','M','Quan sát','SRC-05,SRC-06','Phạm vi dữ liệu theo người phụ trách cần xác nhận'),
('CON-003','Tư vấn','ROL-02,ROL-03','Cập nhật trạng thái tư vấn','Là cán bộ, tôi muốn cập nhật tiến độ xử lý.','Người có consultations.update phải chuyển trạng thái hợp lệ và ghi lịch sử.','BR-16','Given có quyền và chuyển trạng thái hợp lệ When lưu Then cập nhật và tạo history; Given trạng thái sai Then từ chối; Given không quyền Then 403.','Must','M','Quan sát','SRC-04,SRC-05','Ma trận chuyển trạng thái cần xác nhận'),
('USR-001','Nhân sự','ROL-03','Quản lý tài khoản','Là Super Admin, tôi muốn tạo/sửa/khóa tài khoản quản trị.','Chỉ SUPER_ADMIN hoặc quyền admins.* tương ứng được thao tác tài khoản.','BR-17','Given Super Admin và dữ liệu hợp lệ When tạo/sửa/khóa Then lưu và audit; Given QTV Cấp 2 When truy cập/thao tác Then 403 hoặc ẩn menu; Given username trùng Then báo lỗi.','Must','L','Đã xác nhận + Quan sát','SRC-01,SRC-02,SRC-05,SRC-06',''),
('DASH-001','Dashboard','ROL-02,ROL-03','Xem số liệu tổng hợp','Là quản trị viên, tôi muốn xem chỉ số vận hành.','Người có dashboard.view phải xem được số liệu tổng hợp theo dữ liệu hệ thống.','BR-18','Given có quyền When mở dashboard Then hiển thị dữ liệu hoặc trạng thái rỗng; Given API lỗi Then báo lỗi không lộ chi tiết; Given không quyền Then 403.','Should','M','Quan sát','SRC-02,SRC-05,SRC-06','Định nghĩa/KPI và kỳ số liệu cần xác nhận'),
('SITE-001','Nội dung website','ROL-02,ROL-03','Cập nhật khối nội dung','Là quản trị viên, tôi muốn cập nhật nội dung cấu hình theo trang/locale.','Người có quyền phù hợp phải upsert SiteContent theo key duy nhất và cờ published.','BR-19','Given key/locale/value hợp lệ và có quyền When lưu Then upsert; Given payload sai Then từ chối; Given chưa published Then API công khai không trả; Given không quyền Then 403.','Could','L','Quan sát','SRC-04,SRC-05,SRC-06','Quyền cụ thể và ownership nội dung cần xác nhận'),
('APP-001','Hồ sơ ứng tuyển','ROL-02,ROL-03','Xem hồ sơ ứng tuyển','Là cán bộ, tôi muốn xem hồ sơ ứng tuyển được ghi nhận.','Người có quyền phù hợp phải xem danh sách Application và trạng thái.','BR-20','Given có quyền When mở danh sách Then hiển thị dữ liệu/phân trang; Given không có dữ liệu Then trạng thái rỗng; Given không quyền Then 403.','Could','M','Quan sát','SRC-02,SRC-04,SRC-05,SRC-06','Nguồn tạo hồ sơ, quy trình xử lý và quyền cần xác nhận'),
('AUD-001','Nhật ký','ROL-03','Tra cứu nhật ký','Là Super Admin, tôi muốn tra cứu hành động nhạy cảm để kiểm soát.','Hệ thống phải ghi và cho phép truy xuất audit theo quyền đối với các hành động được định nghĩa.','BR-21','Given thao tác được audit When hoàn tất/thất bại phù hợp Then tạo log không chứa bí mật; Given Super Admin When tra cứu Then xem được theo bộ lọc; Given QTV Cấp 2 Then bị từ chối nếu không có quyền.','Should','L','Quan sát một phần','SRC-02,SRC-04,SRC-05','UI/API tra cứu audit cần xác nhận'),
('NFR-001','Toàn hệ thống','Tất cả','Bảo mật truy cập','Là chủ hệ thống, tôi muốn dữ liệu và chức năng được bảo vệ.','Hệ thống phải áp dụng RBAC phía server, cookie HttpOnly, băm mật khẩu, CORS giới hạn, rate limit và làm sạch HTML.','BR-22','Given request nhạy cảm không phiên/quyền When gọi Then 401/403; Given HTML độc hại When lưu Then bị làm sạch; Given lỗi Then không lộ secret/stack trong production.','Must','L','Quan sát','SRC-02,SRC-05','Tiêu chuẩn ATTT chính thức cần xác nhận'),
('NFR-002','Toàn hệ thống','Vận hành','Sao lưu và phục hồi','Là đơn vị vận hành, tôi muốn khôi phục dữ liệu và tệp khi có sự cố.','Phải có quy trình sao lưu PostgreSQL và MinIO, mã hóa/phân quyền bản sao và diễn tập phục hồi định kỳ.','BR-23','Given lịch sao lưu được duyệt When đến kỳ Then tạo bản sao và log; Given yêu cầu phục hồi When thực hiện Then đối soát DB-tệp; RPO/RTO và chu kỳ lưu giữ = TBD.','Must','L','Đề xuất BA','SRC-03','RPO/RTO, retention, chủ sở hữu cần xác nhận'),
('NFR-003','Cổng công khai','ROL-01','Khả năng tiếp cận','Là người dùng có nhu cầu hỗ trợ, tôi muốn sử dụng trang bằng bàn phím/công nghệ trợ giúp.','Các luồng trọng yếu phải đáp ứng WCAG 2.1 AA hoặc chuẩn được stakeholder phê duyệt.','BR-24','Given điều hướng bàn phím When dùng trang Then focus rõ và thao tác được; Given ảnh nội dung When hiển thị Then có alt phù hợp; ngưỡng kiểm tra chính thức = TBD.','Should','L','Đề xuất BA','SRC-07','Chuẩn và phạm vi audit cần xác nhận'),
('NFR-004','Toàn hệ thống','Vận hành','Hiệu năng và khả dụng','Là chủ hệ thống, tôi muốn dịch vụ ổn định trong tải dự kiến.','Phải thống nhất SLO cho thời gian đáp ứng, tải đồng thời, uptime và cảnh báo trước nghiệm thu.','BR-25','Given kịch bản tải đã duyệt When kiểm thử Then đáp ứng ngưỡng TBD; Given phụ thuộc lỗi When truy cập Then suy giảm an toàn; uptime/MTTR = TBD.','Should','L','Đề xuất BA','SRC-03','Cần dữ liệu tải và SLO'),
]

rules=[
('BR-01','Locale hỗ trợ','Locale quan sát: vi/en; fallback và mức độ dịch đầy đủ cần xác nhận.'),('BR-02','Nguồn chương trình','Danh mục chương trình hiện quan sát là dữ liệu tĩnh; ownership cập nhật cần xác nhận.'),('BR-03','Công bố tin','Chỉ PUBLISHED và thời điểm công bố hợp lệ được hiển thị công khai.'),('BR-04','Công bố tài nguyên','Chỉ tài nguyên đã công bố và tệp tồn tại được tải công khai.'),('BR-05','Dữ liệu tư vấn','Thông tin liên hệ phải được validation, rate-limit và xử lý theo chính sách dữ liệu được duyệt.'),('BR-06','Phiên quản trị','Phiên dùng token opaque băm, cookie HttpOnly; tài khoản không ACTIVE không được đăng nhập.'),('BR-07','Mật khẩu ban đầu','Tài khoản có mustChangePassword phải đổi mật khẩu.'),('BR-08','Slug tin','Slug là duy nhất; dữ liệu tin phải qua validation.'),('BR-09','HTML an toàn','Chỉ giữ tag/style/schema URL cho phép; loại script/nội dung nguy hiểm.'),('BR-10','Ảnh CMS','JPG/PNG/WebP/AVIF, tối đa 8 MB theo route upload quan sát.'),('BR-11','Lưu trữ tin','Xóa tin là chuyển ARCHIVED theo hành vi quan sát.'),('BR-12','Tệp tài nguyên','Cho phép PDF/Word/Excel/JPEG/PNG; ngưỡng dung lượng hiện mâu thuẫn 25/50 MB.'),('BR-13','Danh mục tham chiếu','Không xóa danh mục còn tài nguyên tham chiếu.'),('BR-14','Xóa tài nguyên','Code quan sát xóa cứng bản ghi; retention/object cleanup cần quyết định.'),('BR-15','Quyền xem tư vấn','Cần consultations.view; phạm vi theo assignee chưa được xác nhận.'),('BR-16','Trạng thái tư vấn','Enum gồm NEW, RECEIVED, CONTACTING, CONSULTED, COMPLETED, UNREACHABLE, CANCELLED; transition matrix TBD.'),('BR-17','Quản trị nhân sự','QTV Cấp 2 không có quyền nhân sự; Super Admin có quyền theo tài liệu.'),('BR-18','KPI dashboard','Cách tính và kỳ báo cáo phải được business owner duyệt.'),('BR-19','SiteContent','Key duy nhất; nội dung công khai phụ thuộc cờ published.'),('BR-20','Hồ sơ ứng tuyển','Quy trình nguồn vào/xử lý/chủ sở hữu chưa được xác nhận.'),('BR-21','Audit','Không ghi secret; phạm vi sự kiện dựa trên enum và xử lý hiện có.'),('BR-22','Kiểm soát an toàn','RBAC server-side, rate limit, CORS, Argon2id, sanitization.'),('BR-23','BCP/DR','RPO/RTO, retention, nơi lưu và lịch diễn tập = TBD.'),('BR-24','Accessibility','Mục tiêu đề xuất WCAG 2.1 AA; cần stakeholder phê duyệt.'),('BR-25','SLO','Ngưỡng hiệu năng/uptime/MTTR = TBD.'),]

openqs=[
('OQ-001','Phạm vi','Ai là Business Owner và ai có quyền phê duyệt BRD/SRS/UAT?','Cao','Cần xác nhận'),
('OQ-002','Nội dung','Có quy trình duyệt 4 mắt trước khi xuất bản tin/tài nguyên không?','Cao','Cần xác nhận'),
('OQ-003','Tư vấn','Ma trận chuyển trạng thái, SLA liên hệ và quy tắc phân công là gì?','Cao','Cần xác nhận'),
('OQ-004','Dữ liệu cá nhân','Cơ sở pháp lý, nội dung consent, retention và quyền xóa/xuất dữ liệu là gì?','Cao','Cần xác nhận'),
('OQ-005','Tệp','Chọn ngưỡng upload tài nguyên 25 MB hay 50 MB; có quét malware không?','Cao','Cần xác nhận'),
('OQ-006','Xóa','Xóa tài nguyên là soft delete hay hard delete; có xóa object MinIO không?','Cao','Cần xác nhận'),
('OQ-007','Hồ sơ','Nguồn tạo Application và quy trình xử lý/nghiệm thu module này?','Cao','Cần xác nhận'),
('OQ-008','Vận hành','RPO, RTO, uptime, tải đồng thời, retention log và người trực vận hành?','Cao','Cần xác nhận'),
('OQ-009','Tích hợp','SMTP, CRM webhook, Redis, CDN/domain production nào bắt buộc?','Trung bình','Cần xác nhận'),
('OQ-010','Nghiệm thu','Môi trường UAT, bộ dữ liệu mẫu, thiết bị/trình duyệt và người ký nghiệm thu?','Cao','Cần xác nhận'),
]

def shade(cell,fill):
    tcPr=cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def set_repeat(row):
    trPr=row._tr.get_or_add_trPr(); e=OxmlElement('w:tblHeader'); e.set(qn('w:val'),'true'); trPr.append(e)
def setup(doc,title,code):
    sec=doc.sections[0]; sec.page_width=Inches(8.5); sec.page_height=Inches(11); sec.top_margin=sec.bottom_margin=sec.left_margin=sec.right_margin=Inches(1)
    styles=doc.styles
    styles['Normal'].font.name='Calibri'; styles['Normal'].font.size=Pt(10.5); styles['Normal'].paragraph_format.space_after=Pt(6); styles['Normal'].paragraph_format.line_spacing=1.1
    for s,size,col,b,a in [('Title',24,'1F4D78',0,12),('Heading 1',16,'2E74B5',16,8),('Heading 2',13,'2E74B5',12,6),('Heading 3',12,'1F4D78',8,4)]:
        st=styles[s]; st.font.name='Calibri'; st.font.size=Pt(size); st.font.color.rgb=RGBColor.from_string(col); st.font.bold=True; st.paragraph_format.space_before=Pt(b); st.paragraph_format.space_after=Pt(a); st.paragraph_format.keep_with_next=True
    h=sec.header.paragraphs[0]; h.text=f'VGG PLATFORM  |  {code}  |  DRAFT v0.1'; h.style=styles['Caption']
    f=sec.footer.paragraphs[0]; f.alignment=WD_ALIGN_PARAGRAPH.CENTER
    f.add_run('Tài liệu Draft — '); fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'PAGE'); f._p.append(fld)
    doc.add_heading(title,0); p=doc.add_paragraph(); p.add_run('Viện Sau Đại học – Trường Đại học Văn Lang').bold=True
    meta=[['Mã tài liệu',code],['Phiên bản','v0.1'],['Trạng thái','Draft'],['Ngày lập',D],['Người phê duyệt','Cần xác nhận'],['Phân loại nguồn','Xác nhận tài liệu / Quan sát hệ thống / Đề xuất BA / Cần xác nhận']]
    table(doc,meta,header=False,widths=[1.7,4.7]); doc.add_paragraph('Lưu ý: Tài liệu không chứa mật khẩu, token, khóa API hoặc dữ liệu cá nhân không cần thiết.',style='Intense Quote'); doc.add_page_break()
def table(doc,rows,header=True,widths=None):
    t=doc.add_table(rows=len(rows),cols=len(rows[0])); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid'; t.autofit=False
    for i,row in enumerate(rows):
        for j,v in enumerate(row):
            c=t.cell(i,j); c.text=str(v); c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
            if widths: c.width=Inches(widths[j])
            for p in c.paragraphs: p.paragraph_format.space_after=Pt(2); p.paragraph_format.space_before=Pt(2); p.paragraph_format.keep_together=True
        if i==0 and header:
            set_repeat(t.rows[0])
            for c in t.rows[0].cells: shade(c,'1F4D78');
            for c in t.rows[0].cells:
                for r in c.paragraphs[0].runs: r.font.bold=True; r.font.color.rgb=RGBColor(255,255,255)
    doc.add_paragraph()
    return t
def bullets(doc,items):
    for x in items: doc.add_paragraph(x,style='List Bullet')
def history(doc,code):
    doc.add_heading('Kiểm soát tài liệu',1); table(doc,[['Phiên bản','Ngày','Trạng thái','Thay đổi','Phê duyệt'],['v0.1',D,'Draft','Khởi tạo từ khảo sát repository và giao diện/mã nguồn','Cần xác nhận']],widths=[.8,1.0,1.0,2.7,1.0])
    doc.add_heading('Nguồn tham chiếu',2); table(doc,[['Mã','Loại','Nguồn','Mục đích']]+[list(x) for x in sources],widths=[.7,.9,2.0,2.8])

def save(doc,path): doc.save(path)

# BRD
d=Document(); setup(d,'TỔNG QUAN NGHIỆP VỤ (BRD)','BRD'); history(d,'BRD')
d.add_heading('1. Bối cảnh và bài toán',1); d.add_paragraph('VGG Platform là nền tảng cổng thông tin và quản trị cho đào tạo sau đại học, kết hợp website công khai, CMS/CRM quản trị và API tập trung. Nhu cầu nghiệp vụ quan sát được là cung cấp thông tin chương trình, tuyển sinh, nghiên cứu, tin tức và tài nguyên; đồng thời giúp cán bộ quản lý nội dung, yêu cầu tư vấn và tài khoản vận hành.')
d.add_paragraph('Chưa có biên bản phê duyệt nhu cầu nghiệp vụ/charter trong nguồn đã khảo sát. Vì vậy các mục tiêu dưới đây là tổng hợp từ tài liệu hiện có và hành vi hệ thống, ở trạng thái Draft.')
d.add_heading('2. Mục tiêu và tiêu chí thành công',1)
table(d,[['Mã','Mục tiêu','Tiêu chí thành công Draft'],['OBJ-01','Cung cấp thông tin sau đại học nhất quán, song ngữ','Người dùng truy cập được các trang trọng yếu VI/EN; mức bao phủ nội dung TBD'],['OBJ-02','Rút ngắn vận hành xuất bản nội dung','Cán bộ có quyền tạo, sửa, công bố và lưu trữ nội dung; SLA/TAT TBD'],['OBJ-03','Quản lý tập trung yêu cầu tư vấn','Yêu cầu hợp lệ được ghi nhận, phân công/theo dõi; SLA liên hệ TBD'],['OBJ-04','Bảo vệ dữ liệu và truy vết thao tác','RBAC server-side, phiên an toàn, audit các thao tác trọng yếu; retention TBD'],['OBJ-05','Sẵn sàng bàn giao vận hành','Có hướng dẫn triển khai, sao lưu/phục hồi và đầu mối; RPO/RTO TBD']],widths=[.8,2.2,3.4])
d.add_heading('3. Stakeholder',1); table(d,[['Nhóm','Vai trò/Lợi ích','Trách nhiệm cần xác nhận'],['Lãnh đạo Viện/Business Owner','Định hướng nội dung, tuyển sinh, KPI','Phê duyệt phạm vi, quy tắc và UAT'],['Phòng/nhóm nội dung','Biên soạn tin, tài nguyên, nội dung web','Chủ sở hữu nội dung và lịch xuất bản'],['Nhóm tuyển sinh/tư vấn','Tiếp nhận và xử lý lead/hồ sơ','SLA, phân công, trạng thái và báo cáo'],['IT/DevOps nhà trường','Hạ tầng, vận hành, backup, an toàn','SLO, RPO/RTO, giám sát, incident'],['Người học/khách truy cập','Tra cứu, tải tài liệu, gửi tư vấn','Cung cấp dữ liệu hợp lệ và đồng ý xử lý'],['Nhóm phát triển/bảo trì','Sửa lỗi, nâng cấp, hỗ trợ','Quản lý thay đổi và phát hành']],widths=[1.5,2.4,2.5])
d.add_heading('4. Phạm vi',1); d.add_heading('4.1 In scope Draft',2); bullets(d,['Website công khai VI/EN: giới thiệu, chương trình, tuyển sinh, nghiên cứu, trải nghiệm, tin, tài nguyên.','Biểu mẫu tư vấn và quản lý vòng đời yêu cầu tư vấn.','CMS tin tức, ảnh, tài nguyên và danh mục.','Xác thực, phiên, RBAC, quản lý tài khoản quản trị.','Dashboard, nội dung website dạng key-value, hồ sơ ứng tuyển ở mức quan sát được.','PostgreSQL, MinIO, triển khai và bàn giao vận hành.'])
d.add_heading('4.2 Out of scope Draft',2); bullets(d,['Hệ thống tuyển sinh đầu-cuối, thanh toán học phí và LMS.','Tích hợp chính thức với CRM/ERP/SIS/email khi chưa có đặc tả và chủ hệ thống.','Cam kết SLA/SLO, RPO/RTO hoặc số liệu tải khi chưa được phê duyệt.','Nội dung marketing, bản dịch và tính chính xác học thuật do đơn vị nghiệp vụ sở hữu.'])
d.add_heading('5. Giả định, ràng buộc và phụ thuộc',1); table(d,[['Loại','Nội dung','Trạng thái'],['Giả định','Nhà trường cung cấp hạ tầng PostgreSQL và object storage tương thích S3.','Cần xác nhận'],['Ràng buộc','Node.js >=22.13, npm workspaces, Next.js/Fastify/Prisma.','Theo tài liệu/code'],['Phụ thuộc','DNS/TLS, SMTP/CRM nếu kích hoạt, chính sách dữ liệu và đầu mối vận hành.','Cần xác nhận'],['Ràng buộc','Không đưa secret vào tài liệu/repository; cấu hình qua biến môi trường.','Theo tài liệu'],['Phụ thuộc','Dữ liệu chương trình/nội dung tĩnh cần owner và quy trình cập nhật.','Cần xác nhận']],widths=[1.1,4.3,1.0])
d.add_heading('6. Rủi ro',1); table(d,[['ID','Rủi ro','Tác động','Ứng phó đề xuất'],['RSK-01','Chưa có owner/phê duyệt và quy trình duyệt nội dung','Sai phạm vi/nội dung công khai','Chốt RACI và workflow trước UAT'],['RSK-02','Ngưỡng upload tài nguyên 25/50 MB không nhất quán','Lỗi vận hành','Thống nhất một ngưỡng, kiểm thử end-to-end'],['RSK-03','Hard delete tài nguyên chưa rõ retention/object cleanup','Mất dữ liệu hoặc rác kho','Chốt chính sách soft-delete/retention'],['RSK-04','Dữ liệu liên hệ chưa có consent/retention rõ','Rủi ro tuân thủ','Phê duyệt notice, retention, quyền truy cập'],['RSK-05','SLO/RPO/RTO và tải chưa xác định','Không đánh giá được sẵn sàng','Đặt ngưỡng và chạy thử có minh chứng'],['RSK-06','Khẳng định “đã kiểm thử” trong handover thiếu evidence đính kèm','Nghiệm thu sai','Thực hiện UAT độc lập, không tự đánh dấu Pass']],widths=[.7,2.5,1.5,1.7])
d.add_heading('7. Quyết định cần đưa ra',1); table(d,[['Mã','Quyết định','Ưu tiên']]+[[q[0],q[2],q[3]] for q in openqs],widths=[.8,4.8,.8])
save(d,BA/'01-business'/f'{PROJECT}_BRD_v0.1_{D}.docx')

# SRS
d=Document(); setup(d,'ĐẶC TẢ YÊU CẦU HỆ THỐNG (SRS)','SRS'); history(d,'SRS')
d.add_heading('1. Phạm vi và nguyên tắc',1); d.add_paragraph('SRS này mô tả yêu cầu có thể kiểm thử cho bản Draft. Workbook REQ là nguồn quản lý chi tiết; tài liệu này không lặp toàn bộ bảng mà tham chiếu theo Requirement ID.')
d.add_heading('2. Role và phân quyền',1); table(d,[['Mã','Role','Public','Dashboard','Tin','Tài nguyên','Tư vấn','Nhân sự/Audit'],['ROL-01','Khách truy cập','Xem/Gửi','Không','Chỉ PUBLISHED','Chỉ PUBLISHED','Tạo mới','Không'],['ROL-02','QTV Cấp 2','Xem','Có','CRUD theo quyền','CRUD theo quyền','Xem/Cập nhật','Không'],['ROL-03','Super Admin','Xem','Có','CRUD','CRUD','Xem/Cập nhật','Toàn quyền']],widths=[.7,1.2,.7,.8,.8,1.0,1.0,1.1])
d.add_paragraph('Lưu ý: quyền được enforcement phía server bằng mã permission. Chi tiết mapping từng permission cần lấy từ bootstrap/DB môi trường và xác nhận trước UAT.')
d.add_heading('3. Quy trình nghiệp vụ',1)
d.add_heading('3.1 Hiện trạng',2); d.add_paragraph('Không có tài liệu AS-IS về quy trình thủ công trước hệ thống. Cần xác nhận với stakeholder; không suy diễn từ code.')
d.add_heading('3.2 Quy trình đề xuất/quan sát được',2); bullets(d,['Xuất bản tin: đăng nhập → tạo/nhập nội dung → upload ảnh → lưu Draft → kiểm tra → chuyển Published → hiển thị công khai. Bước phê duyệt độc lập là đề xuất BA, chưa có trong code.','Tư vấn: khách gửi biểu mẫu → hệ thống validation/rate-limit → tạo NEW → cán bộ xem/phân công → cập nhật trạng thái/ghi chú → đóng. Ma trận chuyển trạng thái và SLA TBD.','Tài nguyên: cán bộ upload tệp + metadata → chọn danh mục/trạng thái → công bố → khách tra cứu/tải. Chính sách xóa/retention TBD.'])
d.add_heading('4. Danh mục yêu cầu chức năng',1)
for mod in sorted(set(r[1] for r in reqs if not r[0].startswith('NFR'))):
    d.add_heading(mod,2)
    rows=[['ID','Tên','Yêu cầu','Nguồn/Trạng thái']]
    for r in reqs:
        if r[1]==mod and not r[0].startswith('NFR'): rows.append([r[0],r[3],r[5],f'{r[10]} — {r[11]}'])
    table(d,rows,widths=[.9,1.5,3.2,.9])
d.add_heading('5. Business Rules',1); table(d,[['ID','Tên','Quy tắc']]+[list(x) for x in rules],widths=[.8,1.5,4.2])
d.add_heading('6. Yêu cầu dữ liệu và tích hợp',1); table(d,[['Đối tượng','Dữ liệu chính','Validation/quan hệ','Nguồn'],['Admin','username, fullName, email, phone, role, status','username duy nhất; role bắt buộc; secret chỉ lưu dạng hash','SRC-04'],['NewsPost','slug, locale, title, category, content, coverImage, status, author','slug duy nhất; author bắt buộc; HTML sanitize','SRC-04,SRC-05'],['ResourceFile','slug, title, category, loại, metadata văn bản, URL/tên/loại/kích thước tệp, status','category bắt buộc; file metadata bắt buộc; FK restrict','SRC-04,SRC-05'],['Consultation','thông tin liên hệ, nhu cầu, lịch, phương thức, trạng thái, assignee','validation + rate limit; lịch sử/ghi chú','SRC-04,SRC-05'],['Application','họ tên, email, phone, programme, status, metadata','Quy trình và validation nghiệp vụ TBD','SRC-04'],['PageVisit','path, locale, visitorId, thời gian','best-effort; retention TBD','SRC-04,SRC-07'],['Tích hợp','PostgreSQL, MinIO; Redis/SMTP/CRM tùy chọn','Endpoint/credential qua môi trường; không ghi secret','SRC-03,SRC-08']],widths=[1.1,2.2,2.3,.8])
d.add_heading('7. Yêu cầu phi chức năng',1); table(d,[['ID','Yêu cầu','Ngưỡng/AC']]+[[r[0],r[5],r[7]] for r in reqs if r[0].startswith('NFR')],widths=[.9,3.1,2.4])
d.add_heading('8. Use Case trọng yếu',1)
ucs=[('UC-01','Đăng và xuất bản tin','ROL-02/03','Có phiên và news.create/update','Tin được lưu; nếu Published thì đủ điều kiện công khai','1. Mở CMS tin. 2. Nhập metadata/nội dung. 3. Upload ảnh. 4. Lưu Draft. 5. Chuyển Published.','Slug trùng; file sai; HTML nguy hiểm; lỗi kho tệp; không quyền → báo lỗi/401/403 và không công bố sai.','NEWS-001..004'),('UC-02','Gửi và xử lý tư vấn','ROL-01, ROL-02/03','Trang công khai hoạt động; cán bộ có quyền','Lead có lịch sử trạng thái; dữ liệu bảo toàn','1. Khách nhập form. 2. Validation/rate-limit. 3. Tạo NEW. 4. Cán bộ mở, phân công, cập nhật.','Dữ liệu sai; bot/rate limit; trạng thái sai; không quyền; lead không tồn tại.','CON-001..003'),('UC-03','Đăng và tải tài nguyên','ROL-02/03, ROL-01','Danh mục tồn tại; cán bộ có quyền','Bản ghi/tệp lưu; tài nguyên công bố tải được','1. Upload tệp. 2. Nhập metadata/danh mục. 3. Công bố. 4. Khách lọc/tải.','Tệp sai/quá lớn; MinIO lỗi; danh mục sai; không quyền; tệp mất.','RES-001..003,PUB-004'),('UC-04','Quản lý tài khoản','ROL-03','Super Admin có phiên/quyền','Tài khoản thay đổi và có audit','1. Mở nhân sự. 2. Tạo/sửa role/trạng thái. 3. Cấp mật khẩu tạm. 4. Người dùng đổi mật khẩu.','Username trùng; role sai; tự khóa tài khoản cuối cùng; QTV cấp 2 truy cập.','USR-001,AUTH-002')]
for uc in ucs:
    d.add_heading(f'{uc[0]} — {uc[1]}',2); table(d,[['Tác nhân',uc[2]],['Điều kiện trước',uc[3]],['Điều kiện sau',uc[4]],['Luồng chính',uc[5]],['Thay thế/ngoại lệ',uc[6]],['Yêu cầu liên quan',uc[7]]],header=False,widths=[1.4,5.0])
d.add_heading('9. Glossary',1); table(d,[['Thuật ngữ','Giải thích'],['CMS','Hệ thống quản trị nội dung.'],['CRM','Quản lý quan hệ/nhu cầu tư vấn của người quan tâm.'],['RBAC','Kiểm soát truy cập theo vai trò và permission.'],['UAT','Kiểm thử chấp nhận của người dùng nghiệp vụ.'],['RPO/RTO','Mức mất dữ liệu tối đa chấp nhận được / thời gian phục hồi mục tiêu.'],['SLO','Mục tiêu mức dịch vụ.'],['MinIO','Kho lưu trữ đối tượng tương thích S3, có thể tự vận hành.'],['TBD','Chưa xác định, cần quyết định.']],widths=[1.4,5.0])
save(d,BA/'02-requirements'/f'{PROJECT}_SRS_v0.1_{D}.docx')

# UAT
d=Document(); setup(d,'KẾ HOẠCH UAT & CHECKLIST BÀN GIAO','UAT-HANDOVER'); history(d,'UAT-HANDOVER')
d.add_heading('1. Mục tiêu và phạm vi UAT',1); d.add_paragraph('Xác nhận các luồng trọng yếu theo Requirement ID/Use Case: đăng nhập và phân quyền, tin tức/ảnh, tài nguyên/tệp, tư vấn, trang công khai, quản trị tài khoản, dữ liệu và vận hành. Kết quả thực tế để trống cho đến khi thực thi.')
d.add_heading('2. Điều kiện bắt đầu/kết thúc',1); table(d,[['Loại','Tiêu chí'],['Entry','Phạm vi v0.1 được duyệt; môi trường UAT ổn định; dữ liệu mẫu phi cá nhân; tài khoản theo role; build/version được cố định; defect tool và người thực hiện đã chỉ định.'],['Exit','100% test Must đã chạy; không còn defect Critical/High mở hoặc có waiver được phê duyệt; quyền truy cập và backup/restore có evidence; Business Owner ký biên bản. Ngưỡng cụ thể TBD.']],widths=[1.0,5.4])
d.add_heading('3. Kịch bản nghiệm thu',1)
tests=[('TC-001','AUTH-001','UC-01','Đăng nhập đúng/sai/khóa/rate-limit','Đúng tạo phiên; sai/khóa bị từ chối an toàn; không lộ thông tin'),('TC-002','AUTH-002','UC-04','Đổi mật khẩu bắt buộc','Không bỏ qua; mật khẩu sai chuẩn bị từ chối; thành công cho phép tiếp tục'),('TC-003','NEWS-001','UC-01','Tạo tin Draft','Lưu dữ liệu hợp lệ; slug trùng báo lỗi; thiếu quyền 403'),('TC-004','NEWS-002,NEWS-003','UC-01','Dán nội dung có định dạng/ảnh clipboard và upload ảnh','Giữ định dạng hỗ trợ; ảnh được lưu/chèn; HTML độc hại bị loại; file sai/quá 8 MB bị từ chối'),('TC-005','NEWS-004,NEWS-005','UC-01','Xuất bản và lưu trữ tin','Chỉ Published hiển thị; Archived không hiển thị; audit tồn tại'),('TC-006','RES-001,RES-002','UC-03','Upload tài nguyên và danh mục','Tệp/metadata hợp lệ được lưu; sai loại/quá ngưỡng/danh mục sai/không quyền bị từ chối'),('TC-007','PUB-004,RES-003','UC-03','Tải và xóa tài nguyên','Tệp công bố tải đúng; tệp ẩn/mất/xóa được xử lý theo chính sách đã duyệt'),('TC-008','CON-001','UC-02','Gửi tư vấn','Dữ liệu hợp lệ tạo NEW; sai/rate-limit bị từ chối'),('TC-009','CON-002,CON-003','UC-02','Lọc/phân công/cập nhật trạng thái tư vấn','Dữ liệu đúng, history tạo; transition sai/không quyền bị từ chối'),('TC-010','USR-001','UC-04','Super Admin quản lý tài khoản; QTV2 truy cập','Super Admin thao tác và audit; QTV2 không thấy/403'),('TC-011','PUB-001..003','UC-01','Trang VI/EN, chương trình và tin công khai','Điều hướng locale đúng; chỉ nội dung công bố; trạng thái lỗi/rỗng rõ'),('TC-012','NFR-001','N/A','Kiểm tra RBAC, cookie, CORS, sanitize, secret','Không bypass; không lộ secret; input độc hại bị kiểm soát'),('TC-013','NFR-002','N/A','Backup và restore PostgreSQL + MinIO','Phục hồi đối soát thành công theo RPO/RTO đã duyệt; evidence đính kèm'),('TC-014','NFR-003','N/A','Keyboard, focus, alt, contrast luồng trọng yếu','Đạt chuẩn/phạm vi được duyệt; defect được ghi nhận'),('TC-015','NFR-004','N/A','Tải và khả dụng','Đạt ngưỡng SLO đã duyệt; kết quả đo đính kèm')]
table(d,[['TC','Req','UC','Kịch bản','Kết quả mong đợi']]+[list(x) for x in tests],widths=[.65,1.0,.7,2.0,2.05])
d.add_heading('4. Biểu ghi thực thi',1); table(d,[['TC','Người thực hiện','Ngày','Kết quả thực tế','Trạng thái','Minh chứng/Defect']]+[[t[0],'','','','Chưa chạy',''] for t in tests],widths=[.7,1.1,.8,1.8,.9,1.1])
d.add_heading('5. Checklist bàn giao',1); checks=['Repository/tag/release xác định','Cấu hình mẫu không chứa secret','Danh sách domain/DNS/TLS','Sơ đồ kiến trúc và port','Migration và dữ liệu khởi tạo','Runbook build/deploy/rollback','Backup/restore DB và MinIO','Monitoring/log/alert và retention','Tài khoản/quyền theo nguyên tắc tối thiểu','Danh mục license/phụ thuộc/dịch vụ','UAT evidence và defect register','Danh sách known issues/waiver','RACI, liên hệ hỗ trợ, SLA','Đào tạo quản trị nội dung','Biên bản bàn giao/nghiệm thu']
table(d,[['STT','Hạng mục','Chủ trì','Trạng thái','Minh chứng/Ghi chú']]+[[i+1,x,'Cần xác nhận','Chưa xác nhận',''] for i,x in enumerate(checks)],widths=[.55,2.8,1.2,1.0,.85])
d.add_heading('6. Quản lý defect và phê duyệt',1); d.add_paragraph('Defect tối thiểu gồm ID, TC/Requirement, mức độ, bước tái hiện, expected/actual, môi trường, evidence, owner, trạng thái và quyết định. Không có test nào được đánh dấu Pass hoặc nghiệm thu trong bản Draft này.')
save(d,BA/'04-uat'/f'{PROJECT}_UAT-HANDOVER_v0.1_{D}.docx')

# Stakeholder report
d=Document(); setup(d,'BÁO CÁO TÓM TẮT CHO STAKEHOLDER','STAKEHOLDER-REPORT')
d.add_heading('1. Thông điệp điều hành',1); d.add_paragraph('VGG Platform đã có nền tảng kỹ thuật tương đối đầy đủ cho cổng thông tin sau đại học và công cụ quản trị nội dung/tư vấn. Tuy nhiên, trạng thái hiện tại chỉ được ghi nhận là “quan sát được từ tài liệu và code”; chưa có đủ bằng chứng để tuyên bố đã nghiệm thu nghiệp vụ hoặc sẵn sàng production theo tiêu chí stakeholder.')
d.add_heading('2. Mục tiêu và phạm vi',1); bullets(d,['Cung cấp thông tin công khai VI/EN về chương trình, tuyển sinh, nghiên cứu, tin và tài nguyên.','Cho phép cán bộ quản trị tin, ảnh/tệp, yêu cầu tư vấn và tài khoản theo quyền.','Vận hành trên kiến trúc Next.js + Fastify + PostgreSQL + MinIO; tích hợp SMTP/CRM/Redis chưa được xác định là bắt buộc.'])
d.add_heading('3. Điểm đã xác minh',1); table(d,[['Nhóm','Kết luận','Mức tin cậy'],['Cấu trúc','Ba ứng dụng frontend/admin/backend trong npm workspace','Tài liệu + code'],['Quyền','Super Admin có nhân sự; QTV Cấp 2 không có nhân sự','README + code/route'],['Tin tức','Draft/Published/Archived, rich-text, upload ảnh MinIO, public API','Code'],['Tài nguyên','Danh mục, metadata, upload/download qua MinIO','Code'],['Tư vấn','Public submit, status/history/assignment và admin view','Code/schema'],['Vận hành','Có handover triển khai, backup/restore và troubleshooting','Tài liệu; chưa xác nhận execution evidence']],widths=[1.2,4.0,1.2])
d.add_heading('4. Vấn đề tồn đọng và rủi ro',1); bullets(d,['Chưa xác định Business Owner, approver và RACI.','Chưa có quy trình duyệt nội dung 4 mắt; code quan sát cho phép role vận hành xuất bản trực tiếp theo permission.','Ngưỡng upload tài nguyên không nhất quán (Admin mặc định 25 MB, backend schema 50 MB).','Chưa rõ chính sách xóa/retention tệp, consent và retention dữ liệu tư vấn.','Application có model/màn hình quan sát nhưng nguồn vào và quy trình nghiệp vụ chưa rõ.','Chưa có SLO, RPO/RTO, dữ liệu tải và evidence UAT chính thức.'])
d.add_heading('5. Quyết định cần đưa ra',1); table(d,[['Ưu tiên','Quyết định','Đầu ra mong muốn'],['1','Owner/approver, phạm vi v0.1 và RACI','BRD/SRS được Reviewed/Approved'],['2','Workflow xuất bản, permission và trạng thái tư vấn','Business Rules chốt'],['3','Consent/retention, xóa tài nguyên, upload limit','Chính sách dữ liệu/tệp'],['4','SLO, RPO/RTO, UAT entry/exit','Kế hoạch nghiệm thu và vận hành'],['5','Tích hợp bắt buộc: SMTP/CRM/Redis/CDN/domain','Danh mục tích hợp và owner']],widths=[.7,3.2,2.5])
d.add_heading('6. Bước tiếp theo đề xuất',1); bullets(d,['Tổ chức workshop 60–90 phút với Business Owner, nội dung, tuyển sinh và IT để đóng OQ-001..010.','Baseline workbook yêu cầu; gán owner/priority và chấp thuận những mục Must.','Chuẩn bị môi trường/dữ liệu UAT và chạy TC-001..015, giữ nguyên cột kết quả thực tế cho người thực thi.','Đóng defect Critical/High hoặc có waiver được phê duyệt; sau đó mới phát hành v1.0 Approved.'])
d.add_paragraph('Không tính phần trăm hoàn thành do chưa có baseline phạm vi và bằng chứng UAT được phê duyệt.',style='Intense Quote')
save(d,BA/'05-reports'/f'{PROJECT}_STAKEHOLDER-REPORT_v0.1_{D}.docx')

# README + Mermaid + data JSON
readme=f'''# Hồ sơ BA — VGG Platform\n\n**Phiên bản hiện hành:** v0.1 — **Trạng thái:** Draft — **Ngày:** {D}\n\n## Danh mục\n\n- `01-business/{PROJECT}_BRD_v0.1_{D}.docx` / `.pdf`: Bối cảnh, mục tiêu, phạm vi, stakeholder, rủi ro và quyết định.\n- `02-requirements/{PROJECT}_SRS_v0.1_{D}.docx` / `.pdf`: Role, quy trình, yêu cầu, rules, dữ liệu, NFR và use case.\n- `02-requirements/{PROJECT}_REQ-WORKBOOK_v0.1_{D}.xlsx`: Nguồn quản lý yêu cầu và traceability.\n- `03-diagrams/*.mmd`: Nguồn Mermaid có thể chỉnh sửa cho use case, activity và ERD.\n- `04-uat/{PROJECT}_UAT-HANDOVER_v0.1_{D}.docx` / `.pdf`: Kế hoạch UAT, kịch bản và checklist bàn giao.\n- `05-reports/{PROJECT}_STAKEHOLDER-REPORT_v0.1_{D}.docx` / `.pdf`: Báo cáo điều hành 2–4 trang.\n- `archive/`: Chỉ lưu phiên bản lỗi thời; không dùng làm baseline hiện hành.\n\n## Cách sử dụng và cập nhật\n\n1. Workbook là nguồn quản lý Requirement/Rule/Traceability/Open Question; SRS tham chiếu ID thay vì sao chép toàn bộ.\n2. Mọi thay đổi phải thêm Change Log, cập nhật version và trạng thái. Không ghi đè bản cũ; chuyển bản superseded vào `archive/`.\n3. Chỉ chuyển `Draft → Reviewed → Approved` khi có người có thẩm quyền và bằng chứng.\n4. Các nhãn nguồn: **Đã xác nhận trong tài liệu**, **Quan sát từ code/giao diện**, **Đề xuất BA**, **Cần xác nhận**. Tính năng có trong code không mặc nhiên là yêu cầu đã duyệt.\n5. Không lưu mật khẩu, token, khóa API hoặc dữ liệu cá nhân thực trong hồ sơ BA/UAT.\n\n## Nguồn khảo sát\n\n{chr(10).join(f'- **{s[0]} — {s[1]}:** `{s[2]}` — {s[3]}' for s in sources)}\n\n## Kiểm soát chất lượng\n\nBản v0.1 phải được kiểm tra ID trùng, AC trống, mapping quyền, liên kết Requirement–Use Case–Test Case và hiển thị Word/PDF/Excel trước bàn giao.\n'''
(BA/'README.md').write_text(readme,encoding='utf-8')
(BA/'03-diagrams'/f'{PROJECT}_USE-CASE_v0.1_{D}.mmd').write_text('''flowchart LR\n  Public[Khách truy cập] --> Portal[Cổng thông tin VI/EN]\n  Public --> Consult[Gửi yêu cầu tư vấn]\n  Public --> Download[Xem tin & tải tài nguyên]\n  L2[QTV Cấp 2] --> Dashboard\n  L2 --> News[Quản lý tin/ảnh]\n  L2 --> Resources[Quản lý tài nguyên]\n  L2 --> CRM[Xử lý tư vấn]\n  SA[Super Admin] --> Dashboard\n  SA --> News\n  SA --> Resources\n  SA --> CRM\n  SA --> Users[Quản lý tài khoản & quyền]\n  SA --> Audit[Nhật ký]\n  note[Đường nét thể hiện hành vi quan sát được; quyền chi tiết cần baseline] -.-> News\n''',encoding='utf-8')
(BA/'03-diagrams'/f'{PROJECT}_ACTIVITY-CONSULTATION_v0.1_{D}.mmd').write_text('''flowchart TD\n A[Khách mở biểu mẫu] --> B[Nhập thông tin]\n B --> C{Validation / rate limit}\n C -- Không đạt --> D[Thông báo lỗi, không tạo lead]\n C -- Đạt --> E[Tạo Consultation: NEW]\n E --> F[Cán bộ có quyền xem danh sách]\n F --> G[Phân công / ghi chú]\n G --> H{Chuyển trạng thái hợp lệ?}\n H -- Không --> I[Từ chối và giữ trạng thái]\n H -- Có --> J[Cập nhật + ConsultationHistory]\n J --> K{Đã kết thúc?}\n K -- Chưa --> G\n K -- Có --> L[COMPLETED/UNREACHABLE/CANCELLED]\n''',encoding='utf-8')
(BA/'03-diagrams'/f'{PROJECT}_ERD_v0.1_{D}.mmd').write_text('''erDiagram\n ROLE ||--o{ ADMIN : assigns\n ROLE ||--o{ ROLE_PERMISSION : grants\n PERMISSION ||--o{ ROLE_PERMISSION : maps\n ADMIN ||--o{ SESSION : owns\n ADMIN ||--o{ NEWS_POST : authors\n ADMIN ||--o{ RESOURCE_FILE : authors\n RESOURCE_CATEGORY ||--o{ RESOURCE_FILE : groups\n ADMIN ||--o{ SITE_CONTENT : authors\n ADMIN ||--o{ CONSULTATION : assigned\n CONSULTATION ||--o{ CONSULTATION_NOTE : has\n CONSULTATION ||--o{ CONSULTATION_HISTORY : tracks\n ADMIN ||--o{ AUDIT_LOG : acts\n ADMIN ||--o{ PASSWORD_RESET_TOKEN : receives\n ROLE { string id PK string code int level }\n ADMIN { string id PK string username string status string roleId FK }\n NEWS_POST { string id PK string slug string status string authorId FK }\n RESOURCE_FILE { string id PK string slug string categoryId FK string fileUrl string status }\n CONSULTATION { string id PK string email string phone string status string assignedAdminId FK }\n APPLICATION { string id PK string email string phone string status }\n PAGE_VISIT { string id PK string path string locale datetime createdAt }\n''',encoding='utf-8')
json.dump({'sources':sources,'roles':roles,'requirements':reqs,'rules':rules,'openQuestions':openqs,'tests':tests},open(ROOT/'work'/'ba-build'/'data.json','w',encoding='utf-8'),ensure_ascii=False,indent=2)
print('DOCS_CREATED',len(reqs),len(rules),len(tests))
